const express = require("express");
const router = express.Router();
const authRoutes = require("./authRoutes");
const platformRoutes = require("./platformRoutes");
const taskRoutes = require("./taskRoutes");
const customPOTDRoute = require('./potdRoutes');
const contestRoute=require('./contestRoute')
const leetcodeUserRouter=require('./platformRoutes/leetcode-user-route');
const gfgUserRouter=require("./platformRoutes/gfg-user-routes");
const codeforcesUserRouter=require('./platformRoutes/codeforces-user-routes');
const SolutionRoute = require('./potdRoutes/solution-routes');
const favouriteListRoute=require('./favouriteListRoute');
const getAllQuestions=require('.././controllers/questionsController');
const ticketRaise=require('./ticketRoutes');
const schedule=require('../controllers/scheduleController');
const timeTable=require('./timetableRoute');
const chat=require('./chatRoutes');
const Issue=require('./IssueRoutes');
router.use("/ticket-Raise",ticketRaise);
router.use("/ques", platformRoutes);
router.use("/auth", authRoutes);
router.use("/tasks", taskRoutes);
router.use('/custom',customPOTDRoute);
router.use('/questions',getAllQuestions.getAllQuestions);
router.use('/leetcode-user',leetcodeUserRouter);
router.use('/gfg-user',gfgUserRouter);
router.use('/codeforces-user',codeforcesUserRouter);
router.use('/fav',favouriteListRoute)
router.use('/solutions',SolutionRoute);
router.use('/contest',contestRoute);
router.use('/tt',timeTable);
router.use('/chat',chat);
router.use('/issue',Issue);
// router.post('/schedule', schedule.createTimetable);
module.exports = router;
